### ISSUE TITLE
I found a few errors. Could you have a look?

### ISSUE THREAD

**Issue by homink** [hyung8758/kaldi_tutorial#1]
Checking disjoint: silence_phones.txt, nonsilence_phones.txt
--> ERROR: silence_phones.txt and nonsilence_phones.txt has overlap: <UNK>

Checking data/local/dict/extra_questions.txt ...
--> reading data/local/dict/extra_questions.txt
--> data/local/dict/extra_questions.txt is OK
--> ERROR validating dictionary directory data/local/dict (see detailed error messages above)

*Error validating directory data/local/dict*

Generating G.fst from lm.arpa...
/home/kwon/3rdParty/kaldi/src/lmbin/arpa2fst --disambig-symbol=#0 --read-symbol-table=data/lang/words.txt -   data/lang/G.fst
ERROR (arpa2fst[5.2.57~1391-97922]:Input():kaldi-io.cc:742) Error opening input stream data/lang/words.txt

[ Stack-Trace: ]

kaldi::MessageLogger::HandleMessage(kaldi::LogMessageEnvelope const&, char const*)
kaldi::MessageLogger::~MessageLogger()
kaldi::Input::Input(std::string const&, bool*)
main
__libc_start_main
/home/kwon/3rdParty/kaldi/src/lmbin/arpa2fst() [0x443ca9]

/home/kwon/3rdParty/kaldi/src/fstbin/fstisstochastic data/lang/G.fst
ERROR (fstisstochastic[5.2.57~1391-97922]:Input():kaldi-io.cc:742) Error opening input stream data/lang/G.f  st

[ Stack-Trace: ]

kaldi::MessageLogger::HandleMessage(kaldi::LogMessageEnvelope const&, char const*)
kaldi::MessageLogger::~MessageLogger()
kaldi::Input::Input(std::string const&, bool*)
fst::ReadFstKaldiGeneric(std::string, bool)
main
__libc_start_main
/home/kwon/3rdParty/kaldi/src/fstbin/fstisstochastic() [0x4450d9]

steps/train_mono.sh --boost-silence 1.25 --nj 2 --cmd utils/run.pl data/train data/lang exp/mono
cat: data/lang/oov.int: 그런 파일이나 디렉터리가 없습니다
[kwon@ssi-dnn-slave-003 hyung8758]$ more data/lang/words.txt
data/lang/words.txt: No such file or directory

**Comment by homink** [comment]
When \<UNK\> is changed to \<SPL\> below in [local/krs_prep_dict.sh](https://github.com/hyung8758/kaldi_tutorial/blob/master/local/krs_prep_dict.sh), it makes no error.

```
echo -e "<SIL>\n<UNK>" >  $save/silence_phones.txt
```

**Comment by hyung8758** [comment]
Hi. Thanks for your comment. I checked the error and it caused a problem. Your change is truly remove the error message but it cannot be a good solution. Since the training model should learn \<SIL\> and \<UNK\> symbols as silence in the whole training process, \<UNK\> should not be removed or changed to other symbols from silence_phones.txt. Furthermore, \<UNK\> which is not a nonsilence phone is still remained in the nonsilence_phones.txt and it has to be deleted from the nonsilence_phones.txt. I changed a few lines in  krs_prep_dict.sh so that the ASR training will be running without any error. just let me know if you found others. Thanks!

**Comment by homink** [comment]
I am trying to understand your recent commit which shows \<UNK\> found in both silence_phones.txt and nonsilence_phones.txt. In my inexperience view, \<UNK\> is used to indicate not belonging to the predefined dictionary, which is nonsilence_phone. But such librispeech recipe has <UNK> as word with silence phone "SPN". Could you help me understand why \<UNK\> is found in both silece_phones.txt and nonsilence_phones.txt??

**Comment by hyung8758** [comment]
It is strange If you found \<UNK\> in both nonsilence_phones.txt and silence_phones.txt because my recent commit removed \<UNK\> from nonsilence_phones.txt but not from silence.txt. \<UNK\> should only be found in silence_phones.txt. Could you remove the original kaldi_tutorial directory and pull it newly again into your local? I hope that gets rid of the error. When it comes to silence phone SPN used in librispeech, librispeech just decided to use SPN as a silence symbol in their training process and the symbol criteria is rather different in my recipe. Since silence symbols could be selected with any words such as '\<thisissielnce\>' or '\<quiet\>' , I chose '\<UNK\>' in my recipe and it should not be switched to any other symbols (for example, SPN) because I already set \<UNK\> in lexicon.txt.
